export interface Tenants {
    tenantID? : any;
    tenantName? : any;
    companyLog? : any;
    companyurl? : any;
    address1? : any;
    address2? : any;
    city? : any;
    state? : any;
    zip? : any;
    country? : any;
    title? : any;
    prefix? : any;
    firstName? : any;
    lastName? : any;
    businessPhone? : any;
    phoneExt? : any;
    mobile? : any;
    email? : any;
    password? : any;
    profilePic? : any;
    isEmailConfirmed?:any;
    allowExport? : any;
    isMultiLocation? : any;
    isMultiCompany? : any;
    isMultilingual? : any;
    isPOS? : any;
    isSuspended? : any;
    subscriptionDate? : any;
    subscriptionEndDate? : any;
    subscriptionType? : any;
    connectionString? : any;
    serverName? : any;
    initialCatalog? : any;
    dbUser? : any;
    dbPass? : any;
    verificationCode? : any;
    notes? : any;
    ordinal? : any;
    active? : any;
    created? : any;
    crtBy? : any;
    updated? : any;
    modBy? : any;
    maxUserCount?:any;
    maxCompaniesCount?:any;
    maxLocationCount?:any;
}
