export class Product {
    barCode?: any;
    discountAmount?: any;
    taxPercent?: any;
    taxAmount?: any;
    taxCode?:any;
    extraDiscountPercent?: any;
    extraDiscountAmount?: any;
    advanceTaxPercent?: any;
    advanceTaxAmount?: any;
    advanceTaxCode?:any;
    extraAdvanceTaxCode?:any;
    extraAdvanceTaxPercent?: any;
    extraAdvanceTaxAmount?: any;
    rebatePercent?: any;
    rebateAmount?: any;
    grossValue?: number;
    discountedGross?: number;
    netAmountBeforeRebate?: any;
    netAmount?: number;
    netRate?: number;
    prodBCID?: any;
    notes?: any;
    batchNo?: any;
    expiry?: any;
    discountPercent?: any;
    prodID ?: any;
    prodGrpID ?: any;
    comID ?: any;
    comName ?: any;
    prodGrpName ?: any;
    prodCode ?: any;
    shortName ?: any;
    prodName ?: any;
    descr ?: any;
    prodUnit ?: any;
    unitQty ?: any;
    qty?:any;
    tax?:any;
    discount?:any;
    purchRate ?: any;
    amount?:any;
    sellRate ?: any;
    batch?:any;
    retailprice ?: any;
    bonusQty?:any;
    tP ?: any;
    qtyBal?:any;
    isDiscount ?: any;
    isTaxable ?: any;
    isStore ?: any;
    isRaw ?: any;
    isBonus ?: any;
    minQty ?: any;
    maxQty ?: any;
    mega ?: any;
    active ?: any;
    crtBy ?: any;
    crtDate ?: any;
    modby ?: any;
    modDate ?: any;
    expirydate ?: any;
    GLID ?: any;
    TxID ?: any;
    unitPrice ?: any;
    taxName?:any;
    barcodeImage?:any;
    vendID?:any;
    vendName?:any;
    ProductBarCodes?: ProductBarCodes[];
    prodManuID?:any;
    depID?:any;
    categoryID?:any;
    isImported?:any;
    prodSize?:any;
    prodColor?:any;
    depName?:any;
    prodManuName?:any;
    categoryName?:any;
    sharePercentage?:any;
    IsUpdate?:boolean;
    supplierIDList?:number[];
}

export class ProductBarCodes {
    prodBCID?: number;
    prodID?: number;
    BarCode?: string;
    Qty?: number;
    Unit?: string;
    Active?: boolean;
    CostPrice? : any;
    SalePrice? : any;
    TradePrice? : any;
    FOBPrice? : any;
    isEditable?: any = false;
  }